window.MOCK = (function () {
  const lecturers = [
    {
      id: "8421",
      name: "BANGGA AGUNG SATRIYA, S.K.M., M.K.M.",
      nidn: "—",
      nidnNote: "NIDN belum tercatat di ringkasan portal",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 3 sks",
      jabatan: "Tenaga Pengajar",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Kesehatan Masyarakat",
      penelitian: 5,
      abdimas: 5,
      kewajiban: 3,
      mk: 5,
      kelas: 9,
      sks: 18,
      maxSks: 18,
      synthetic: false,
      initials: "BA",
    },
    {
      id: "7979",
      name: "DANIEL HAPPY PUTRA, S.KM., M.K.M.",
      nidn: "0319015501",
      nidnNote: "NIDN",
      hrmNip: "219080813",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 6 sks",
      jabatan: "Lektor (300)",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Kesehatan Masyarakat",
      penelitian: 7,
      abdimas: 5,
      kewajiban: 6,
      mk: 5,
      kelas: 9,
      sks: 18,
      maxSks: 18,
      synthetic: false,
      initials: "DH",
    },
    {
      id: "7023",
      name: "DEASY ROSMALA DEWI, SKM, M.KES",
      nidn: "1126037501",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tidak Tetap",
      jabatan: "Asisten Ahli (150)",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Kesehatan Masyarakat",
      penelitian: 1,
      abdimas: 1,
      kewajiban: 0,
      mk: 3,
      kelas: 3,
      sks: 6,
      maxSks: 11,
      synthetic: false,
      initials: "DR",
    },
    {
      id: "8274",
      name: "DINA SONIA, S.ST., MM",
      nidn: "0423015201",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 12 sks",
      jabatan: "Lektor (200)",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Kesehatan Masyarakat",
      penelitian: 6,
      abdimas: 3,
      kewajiban: 12,
      mk: 5,
      kelas: 8,
      sks: 21,
      maxSks: 21,
      synthetic: false,
      initials: "DS",
    },
    {
      id: "6997",
      name: "dr. NOOR YULIA, MM",
      nidn: "0315076308",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tidak Tetap",
      jabatan: "Lektor (200)",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Ilmu Kedokteran",
      penelitian: 2,
      abdimas: 1,
      kewajiban: 0,
      mk: 2,
      kelas: 4,
      sks: 10,
      maxSks: 11,
      synthetic: false,
      initials: "NY",
    },
    {
      id: "6936",
      name: "LAELA INDAWATI, SST, M.K.M.",
      nidn: "0306057803",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 12 sks",
      jabatan: "Lektor (300)",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Kesehatan Masyarakat",
      penelitian: 4,
      abdimas: 1,
      kewajiban: 12,
      mk: 4,
      kelas: 7,
      sks: 18,
      maxSks: 18,
      synthetic: false,
      initials: "LI",
    },
    {
      id: "5196",
      name: "LILY WIDJAJA, SKM, MM.",
      nidn: "8870170018",
      nidnNote: "NIDK",
      kriteria: "NIDK",
      kelompok: "Pengajar Non Dosen",
      jabatan: "Asisten Ahli (100)",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Kesehatan Masyarakat",
      penelitian: 0,
      abdimas: 0,
      kewajiban: 0,
      mk: 2,
      kelas: 2,
      sks: 5,
      maxSks: 11,
      synthetic: false,
      initials: "LW",
    },
    {
      id: "8343",
      name: "MUHAMMAD FUAD IQBAL, S.K.M, M.K.M.",
      nidn: "0320019301",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 12 sks",
      jabatan: "Asisten Ahli (150)",
      homebase: "Fikes / Rekam Medis",
      rumpun: "Kesehatan Masyarakat",
      penelitian: 4,
      abdimas: 7,
      kewajiban: 12,
      mk: 4,
      kelas: 9,
      sks: 22,
      maxSks: 22,
      synthetic: false,
      initials: "MF",
    },
    {
      id: "s-1102",
      name: "RINA MAHARANI, S.Kom., M.T.",
      nidn: "0012048801",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 12 sks",
      jabatan: "Lektor (200)",
      homebase: "Fasilkom / Informatika",
      rumpun: "Ilmu Komputer",
      penelitian: 3,
      abdimas: 2,
      kewajiban: 12,
      mk: 3,
      kelas: 4,
      sks: 9,
      maxSks: 16,
      synthetic: true,
      initials: "RM",
    },
    {
      id: "s-2218",
      name: "ANDI PRABOWO, S.E., M.M.",
      nidn: "0022087904",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 12 sks",
      jabatan: "Lektor Kepala (400)",
      homebase: "FE / Manajemen",
      rumpun: "Ilmu Manajemen",
      penelitian: 8,
      abdimas: 4,
      kewajiban: 12,
      mk: 6,
      kelas: 10,
      sks: 24,
      maxSks: 24,
      synthetic: true,
      initials: "AP",
    },
    {
      id: "s-3340",
      name: "SITI NURHALIZA, S.Kep., Ns., M.Kep.",
      nidn: "0015119002",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 6 sks",
      jabatan: "Asisten Ahli (150)",
      homebase: "Fikes / Keperawatan",
      rumpun: "Ilmu Keperawatan",
      penelitian: 2,
      abdimas: 3,
      kewajiban: 6,
      mk: 2,
      kelas: 3,
      sks: 8,
      maxSks: 16,
      synthetic: true,
      initials: "SN",
    },
    {
      id: "s-4401",
      name: "BIMA SAKTI, S.H., M.H.",
      nidn: "0009078509",
      nidnNote: "NIDN",
      kriteria: "NIDN Penuh Waktu",
      kelompok: "Tetap 12 sks",
      jabatan: "Lektor (300)",
      homebase: "FH / Ilmu Hukum",
      rumpun: "Ilmu Hukum",
      penelitian: 5,
      abdimas: 1,
      kewajiban: 12,
      mk: 5,
      kelas: 7,
      sks: 20,
      maxSks: 20,
      synthetic: true,
      initials: "BS",
    },
  ];

  const teaching = {
    7979: [
      { periode: "2026/2027 Ganjil", kode: "RME131", nama: "Pengantar Teknologi Informasi" },
      { periode: "2026/2027 Ganjil", kode: "KSM231", nama: "Sistem Informasi Kesehatan" },
      { periode: "2025/2026 Genap", kode: "CRK464", nama: "Analisis Dan Perancangan Sistem" },
      { periode: "2025/2026 Genap", kode: "RMK161", nama: "Algoritma dan Pemrograman" },
      { periode: "2025/2026 Ganjil", kode: "RMK160", nama: "Aplikasi Perangkat Lunak Rekam Medis" },
      { periode: "2025/2026 Ganjil", kode: "RMK263", nama: "Basis Data dan Analisis Perancangan Sistem" },
      { periode: "2024/2025 Genap", kode: "RMK665", nama: "Sistem Informasi Geografis" },
    ],
    8421: [
      { periode: "2026/2027 Ganjil", kode: "RMK160", nama: "Aplikasi Perangkat Lunak Rekam Medis" },
      { periode: "2025/2026 Genap", kode: "RMK263", nama: "Basis Data dan Analisis Perancangan Sistem" },
    ],
    7023: [
      { periode: "2026/2027 Ganjil", kode: "RKE110", nama: "Terminologi Medis" },
      { periode: "2025/2026 Genap", kode: "RKE211", nama: "Klasifikasi dan Kodefikasi Penyakit" },
    ],
    8274: [
      { periode: "2026/2027 Ganjil", kode: "RKE313", nama: "Manajemen Unit Kerja RMIK" },
      { periode: "2025/2026 Genap", kode: "RKE414", nama: "Mutu Pelayanan Rekam Medis" },
    ],
    6997: [
      { periode: "2026/2027 Ganjil", kode: "RKE212", nama: "Anatomi Fisiologi" },
      { periode: "2025/2026 Genap", kode: "RKE251", nama: "Patofisiologi" },
    ],
    6936: [
      { periode: "2026/2027 Ganjil", kode: "RKE363", nama: "Statistik Pelayanan Kesehatan" },
      { periode: "2025/2026 Genap", kode: "RKE502", nama: "Epidemiologi" },
    ],
    5196: [
      { periode: "2026/2027 Ganjil", kode: "UEU101", nama: "Pendidikan Pancasila" },
      { periode: "2025/2026 Genap", kode: "UNV321", nama: "Bahasa Indonesia" },
    ],
    8343: [
      { periode: "2026/2027 Ganjil", kode: "RKE515", nama: "Utilisasi Review" },
      { periode: "2025/2026 Genap", kode: "RKE516", nama: "Manajemen Klaim" },
    ],
    "s-1102": [
      { periode: "2026/2027 Ganjil", kode: "INF210", nama: "Struktur Data" },
      { periode: "2025/2026 Genap", kode: "INF330", nama: "Basis Data Lanjut" },
    ],
    "s-2218": [
      { periode: "2026/2027 Ganjil", kode: "MNJ401", nama: "Manajemen Strategik" },
      { periode: "2025/2026 Genap", kode: "MNJ220", nama: "Perilaku Organisasi" },
    ],
    "s-3340": [
      { periode: "2026/2027 Ganjil", kode: "KEP201", nama: "Keperawatan Medikal Bedah" },
      { periode: "2025/2026 Genap", kode: "KEP110", nama: "Dasar Keperawatan" },
    ],
    "s-4401": [
      { periode: "2026/2027 Ganjil", kode: "HKM301", nama: "Hukum Perdata" },
      { periode: "2025/2026 Genap", kode: "HKM210", nama: "Pengantar Ilmu Hukum" },
    ],
  };

  const profiles = {
    7979: {
      scholar: "https://scholar.google.com/citations?user=xkWCN1MAAAAJ&hl=en",
      sinta: "6751829",
      education: [
        { jenjang: "Sarjana", institusi: "Universitas Sumatera Utara", tahun: "2015" },
        { jenjang: "Magister", institusi: "Universitas Indonesia", tahun: "2018" },
      ],
    },
  };

  const rps = {
    RME131: {
      nama: "Pengantar Teknologi Informasi",
      kode: "RME131",
      fakultas: "Fakultas Ilmu-Ilmu Kesehatan",
      prodi: "Rekam Medik dan Informasi Kesehatan",
      rumpunMk: "—",
      sks: "T=1 · P=2",
      semester: "1",
      tanggal: "1 September 2026",
      pengembang: "DANIEL HAPPY PUTRA, S.KM., M.K.M.",
      koordinator: "DANIEL HAPPY PUTRA, S.KM., M.K.M.",
      ketuaProdi: "DANIEL HAPPY PUTRA, S.KM., M.K.M.",
      pengampu: [
        "DANIEL HAPPY PUTRA, S.KM., M.K.M.",
        "DINA SONIA, S.ST., MM",
      ],
      deskripsi:
        "Mata kuliah pengantar teknologi informasi dan sistem informasi kesehatan untuk mahasiswa RMIK. Membahas ekosistem kesehatan digital, rekam medis elektronik, tata kelola data, keamanan informasi, keterampilan digital dasar, serta tren telemedicine, wearable, AI, dan Big Data.",
      cpl: [
        {
          kode: "CPL3",
          teks: "Mampu mensintesis ilmu medis dasar (anatomi, fisiologi, patofisiologi dan terminologi medis) dengan arsitektur kesehatan digital dan tata kelola data untuk menjamin akurasi, integritas, serta interoperabilitas data rekam medis elektronik sesuai standar nasional dan internasional.",
        },
        {
          kode: "CPL5",
          teks: "Mampu mengolah dan menganalisis data kesehatan menggunakan metode statistik serta epidemiologi untuk menghasilkan informasi yang akurat guna mendukung pengambilan keputusan klinis, manajerial, dan kebijakan kesehatan masyarakat.",
        },
      ],
      ik: [
        {
          kode: "IK3C",
          teks: "Mampu mengelola variabel dan metadata kesehatan sesuai standar interoperabilitas internasional (HL7/FHIR). (CPL3)",
        },
        {
          kode: "IK3E",
          teks: "Mampu menerapkan strategi tata kelola data (Data Governance) dan kebijakan keamanan informasi kesehatan digital. (CPL3)",
        },
        {
          kode: "IK5F",
          teks: "Mampu memodelkan prediksi utilisasi sumber daya fasyankes menggunakan machine learning dan teknik regresi. (CPL5)",
        },
      ],
      cpmk: [
        {
          kode: "CPMK1",
          teks: "Mahasiswa mampu menjelaskan konsep dasar sistem informasi kesehatan, fungsi Rekam Medis Elektronik (RME), serta mengenali pentingnya standar data dan interoperabilitas dalam pelayanan kesehatan modern. (IK5F)",
        },
        {
          kode: "CPMK2",
          teks: "Mahasiswa mampu menjelaskan dan menerapkan prinsip dasar privasi, kerahasiaan informasi pasien, serta praktik keamanan internet di lingkungan fasyankes. (IK3E)",
        },
        {
          kode: "CPMK3",
          teks: "Mahasiswa mampu mengenali dan mengeksplorasi tren teknologi kesehatan terbaru, termasuk konsep dasar telemedicine, perangkat wearable, AI, dan Big Data. (IK3C)",
        },
        {
          kode: "CPMK4",
          teks: "Mahasiswa mampu mempraktikkan keterampilan dasar komputer dan menggunakan perangkat lunak (seperti spreadsheet, aplikasi web sederhana, dan reference manager) untuk mendukung tugas administrasi dan akademik dasar. (IK3C, IK3E)",
        },
      ],
      subCpmk: [
        {
          kode: "Sub-CPMK1",
          minggu: 1,
          teks: "Mahasiswa mampu menjelaskan peran profesi RMIK dalam ekosistem kesehatan digital dan transformasi nasional. (CPMK1)",
        },
        {
          kode: "Sub-CPMK2",
          minggu: 2,
          teks: "Mahasiswa mampu menguraikan dasar hukum Rekam Medis Elektronik (PMK 24/2022) dan tujuan platform SATUSEHAT. (CPMK1)",
        },
        {
          kode: "Sub-CPMK3",
          minggu: 3,
          teks: "Mahasiswa mampu membedakan jenis-jenis Sistem Informasi Kesehatan (EHR, EMR, PHR). (CPMK1)",
        },
        {
          kode: "Sub-CPMK4",
          minggu: 4,
          teks: "Mahasiswa mampu menerapkan prinsip dasar tata kelola data kesehatan menggunakan konsep piramida DIKW. (CPMK1)",
        },
        {
          kode: "Sub-CPMK5",
          minggu: 5,
          teks: "Mahasiswa mampu mengenali konsep dasar interoperabilitas dan pengantar standar pertukaran data klinis global (HL7/FHIR). (CPMK1)",
        },
        {
          kode: "Sub-CPMK6",
          minggu: 6,
          teks: "Mahasiswa mampu mengidentifikasi ancaman keamanan siber dasar (CIA Triad, phishing, ransomware) di fasilitas kesehatan. (CPMK2)",
        },
        {
          kode: "Sub-CPMK7",
          minggu: 7,
          teks: "Mahasiswa mampu menerapkan prinsip etika, privasi, dan kerahasiaan data pasien sesuai regulasi perlindungan data. (CPMK2)",
        },
        {
          kode: "Sub-CPMK8",
          minggu: 8,
          teks: "Mahasiswa mampu menggunakan perangkat lunak spreadsheet dasar untuk tugas administrasi kesehatan. (CPMK4)",
        },
        {
          kode: "Sub-CPMK9",
          minggu: 9,
          teks: "Mahasiswa mampu mempraktikkan teknik pembersihan data sederhana dan pembuatan grafik visualisasi laporan dasar. (CPMK4)",
        },
        {
          kode: "Sub-CPMK10",
          minggu: 10,
          teks: "Mahasiswa mampu menggunakan perangkat digital untuk penelusuran literatur kesehatan dan mengoperasikan reference manager. (CPMK4)",
        },
        {
          kode: "Sub-CPMK11",
          minggu: 11,
          teks: "Mahasiswa mampu mendeskripsikan komponen, regulasi, dan manfaat Telemedicine / Telehealth di ekosistem kesehatan Indonesia. (CPMK3)",
        },
        {
          kode: "Sub-CPMK12",
          minggu: 12,
          teks: "Mahasiswa mampu mengeksplorasi konsep perangkat wearable (IoMT) dan dampaknya terhadap data pasien. (CPMK3)",
        },
        {
          kode: "Sub-CPMK13",
          minggu: 13,
          teks: "Mahasiswa mampu menjelaskan secara konseptual peran Artificial Intelligence (AI) dan Big Data dalam efisiensi pelayanan kesehatan. (CPMK3)",
        },
        {
          kode: "Sub-CPMK14",
          minggu: 14,
          teks: "Mahasiswa mampu menguraikan tahapan Siklus Hidup Pengembangan Sistem (SDLC) untuk memahami alur pemilihan vendor RME. (CPMK1, CPMK3)",
        },
      ],
      pertemuan: [
        { minggu: 1, sub: "Sub-CPMK1", bentuk: "Kuliah, diskusi", metode: "Ceramah, diskusi kelompok", bobot: "5%" },
        { minggu: 2, sub: "Sub-CPMK2", bentuk: "Kuliah, studi kasus", metode: "Studi kasus PMK 24/2022", bobot: "5%" },
        { minggu: 3, sub: "Sub-CPMK3", bentuk: "Kuliah, diskusi", metode: "Perbandingan EHR/EMR/PHR", bobot: "5%" },
        { minggu: 4, sub: "Sub-CPMK4", bentuk: "Kuliah, praktik", metode: "Latihan DIKW", bobot: "5%" },
        { minggu: 5, sub: "Sub-CPMK5", bentuk: "Kuliah, praktik", metode: "Pengenalan HL7/FHIR", bobot: "5%" },
        { minggu: 6, sub: "Sub-CPMK6", bentuk: "Kuliah, simulasi", metode: "Simulasi ancaman siber", bobot: "5%" },
        { minggu: 7, sub: "Sub-CPMK7", bentuk: "Kuliah, diskusi", metode: "Studi kasus privasi data", bobot: "5%" },
        { minggu: 8, sub: "Sub-CPMK8", bentuk: "Praktikum", metode: "Latihan spreadsheet", bobot: "10%" },
        { minggu: 9, sub: "Sub-CPMK9", bentuk: "Praktikum", metode: "Data cleaning dan visualisasi", bobot: "10%" },
        { minggu: 10, sub: "Sub-CPMK10", bentuk: "Praktikum", metode: "Reference manager", bobot: "5%" },
        { minggu: 11, sub: "Sub-CPMK11", bentuk: "Kuliah, diskusi", metode: "Studi kasus telemedicine", bobot: "5%" },
        { minggu: 12, sub: "Sub-CPMK12", bentuk: "Kuliah, eksplorasi", metode: "Eksplorasi IoMT", bobot: "5%" },
        { minggu: 13, sub: "Sub-CPMK13", bentuk: "Kuliah, diskusi", metode: "Diskusi AI dan Big Data", bobot: "5%" },
        { minggu: 14, sub: "Sub-CPMK14", bentuk: "Kuliah, project", metode: "Kajian SDLC dan vendor RME", bobot: "10%" },
      ],
      penilaian: [
        "Partisipasi dan diskusi kelas 10%",
        "Tugas terstruktur (minggu 1–7) 25%",
        "Praktik laboratorium / spreadsheet 25%",
        "UTS 20%",
        "UAS / project kajian 20%",
      ],
      referensi: [
        "Peraturan Menteri Kesehatan Republik Indonesia Nomor 24 Tahun 2022 tentang Rekam Medis.",
        "HL7 International. Fast Healthcare Interoperability Resources (FHIR) Overview.",
        "Wager, K. A., Lee, F. W., & Glaser, J. P. Health Care Information Systems. Wiley.",
        "Undang-Undang Nomor 27 Tahun 2022 tentang Pelindungan Data Pribadi.",
      ],
    },
  };

  function statusOf(row) {
    if (row.sks > row.maxSks) return "over";
    if (row.sks === row.maxSks) return "at_max";
    return "under";
  }

  function headroom(row) {
    return row.maxSks - row.sks;
  }

  return { lecturers, teaching, profiles, rps, statusOf, headroom };
})();
